Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
vw = pyvw.vw("--search 0 --csoaa_ldf m --search_task hook --ring_size 1024 --quiet")
task = vw.init_search_task(CovingtonDepParserLDF)
#BUG: This currently does not work because oracle generation is incorrect (generates invalid oracle values)#for p in range(2): # do two passes over the training data
#    task.learn(my_dataset)
#print(task.predict( [(w,-1) for w in "the monster ate a sandwich".split()] ))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Input [0;32mIn [14][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m vw [38;5;241m=[39m [43mpyvw[49m[38;5;241;43m.[39;49m[43mvw[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m--search 0 --csoaa_ldf m --search_task hook --ring_size 1024 --quiet[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m task [38;5;241m=[39m vw[38;5;241m.[39minit_search_task(CovingtonDepParserLDF)

File [0;32m/usr/local/lib/python3.9/site-packages/vowpalwabbit/pyvw.py:389[0m, in [0;36mvw.__init__[0;34m(self, arg_str, enable_logging, **kw)[0m
[1;32m    387[0m     [38;5;28msuper[39m(vw, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m[38;5;241m.[39mjoin(l), [38;5;28mself[39m[38;5;241m.[39m_log_wrapper)
[1;32m    388[0m [38;5;28;01melse[39;00m:
[0;32m--> 389[0m     [38;5;28;43msuper[39;49m[43m([49m[43mvw[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m [39;49m[38;5;124;43m"[39;49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[43ml[49m[43m)[49m[43m)[49m
[1;32m    390[0m [38;5;28mself[39m[38;5;241m.[39minit [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    392[0m [38;5;66;03m# check to see if native parser needs to run[39;00m

[0;31mRuntimeError[0m: Tried to use a multiline reduction as a singleline reduction. Name: shared_feature_merger
RuntimeError: Tried to use a multiline reduction as a singleline reduction. Name: shared_feature_merger

